vich_uploader:
    db_driver: orm

    mappings:
        img_house:
            uri_prefix: /images/house
            upload_destination: '%kernel.project_dir%/public/images/house'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
